### ISSUE TITLE
Result Video blurry

### ISSUE THREAD

**Issue by wfengchen** [soumik-kanad/diff2lip#13]
I have encountered some issues. I input a video in 1080p resolution. After processing, the output is also in 1080p, but the video is very blurry and doesn't achieve a high-quality result. How can I adjust this? Please assist me. Thank you.

INPUT LIKE:
![1 1](https://github.com/soumik-kanad/diff2lip/assets/5045147/944703e9-91dd-4139-b61f-6fa98294a8f1)

OUTPUT LIKE:
![1 2](https://github.com/soumik-kanad/diff2lip/assets/5045147/b8c05b4c-f00c-4ecb-a327-e6a474472430)

**Comment by soumik-kanad** [comment]
If I had to guess, I would say this is happening because the generate script uses ffmpeg to extract the frame ([here](https://github.com/soumik-kanad/diff2lip/blob/6d082c4132e4db8da49271ce8a54f9b318c084ae/generate.py#L71)) and consequently might compress the images. This was done to make sure that the frames saved on the disk don't occupy too much space. You can probably update this code to be able to save the frames at full quality. 

Even with that there might be degradation in results in this case because the model is not trained with HD data and resizes the face to 128x128, so HD focused faces might have blurry results.
